-- MySQL Script generated by MySQL Workbench
-- Wed Nov  7 21:27:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema DMD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DMD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DMD` ;
USE `DMD` ;

-- -----------------------------------------------------
-- Table `DMD`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DMD`.`Car` (
  `Registration_number` INT NOT NULL,
  `Type` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Charge_level_in_MaH` INT NULL,
  `Full_charge_in_MaH` INT NULL,
  `Busy` TINYINT NULL,
  `Condition` TINYINT NULL,
  PRIMARY KEY (`Registration_number`),
  UNIQUE INDEX `Registration_Number_UNIQUE` (`Registration_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DMD`.`Workshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DMD`.`Workshop` (
  `id` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `Available_timing` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
